commodity.csv

Diamond issue #4 and minerals from issue #3

diamonds and minerals

---

commodity.csv

"Ion Distributor" is in category "Machinery"
"Trinkets Of Hidden Fortune" is in category "Consumer Items"
"Landmines" have 4602 as average

Data update

---

factionstate.csv

As seen in a FSDJump payload:
```json
{
"Allegiance": "Independent",
"FactionState": "None",
"Influence": 0.038038,
"Name": "New Hang Po Focus",
"Government": "Dictatorship"
}
```

Add None localization to factionstate.csv

---

commodity.csv

this is the only one which i was unsure about....setting it to UnknownArtifact3 after reading Marginal's comment

changed thargoid link

---

outfitting.csv

To answer the obvious question, yes, the class/rating is that strange: 
Raw data attached for reference
[HIP 13644.Herndon Penal colony.2017-12-01T18.56.48.json.txt](https://github.com/EDCD/FDevIDs/files/1522530/HIP.13644.Herndon.Penal.colony.2017-12-01T18.56.48.json.txt)

New weapons from the fifth Aegis CG

---

outfitting.csv

Armour for the new Type-10 Defender.  Ship and Armour are marked Horizons only in the raw JSON.

Armour for the new Type-10 Defender

---

outfitting.csv

4 x Recon Limpet Controller
5 x Armour for the new Alliance Chieftain

new modules with 3.0

---

outfitting.csv

* you missed some lines
* and I guess the _Fixed_ in line 984 means also guidance
* powerplay modules update

really ensure all lines have 10 fields

---

commodity.csv
rare_commodity.csv

* added list of known rare commodities

Rare commodities

---

outfitting.csv

Add missing mount and guidance information

---

outfitting.csv
sku.csv

SKU values for LYR and the pack-hound missile rack

Powerplay Li Yong-Rui

---

outfitting.csv

two more SKU decoded, next one in four weeks

add powerplay modules of Hudson and ALD

---

outfitting.csv
sku.csv

Also add missing sku.csv entries for ALD and ZH

powerplay Zemina Torval

---

outfitting.csv
sku.csv

Another month, another power filled in

Powerplay Aisling Duval

---

happiness.csv

Someone did search for it, so why not.

Added happiness values.

---

outfitting.csv
sku.csv

New advanced multi-cannon from the "Bridging the Gap" interstellar initiative
Powerplay
- add SKU value for Pranav Antal
- correct name for Pranav Antal's special weapon from "Enforcer multi-cannon" to
"Enforcer Cannon" to match in-game display, correct SKU as well

Advanced Multi-Cannon and Pranav Antal

---

outfitting.csv
sku.csv

And the next power, Edmund Mahon.

Powerplay: Edmund Mahon

---

economy.csv

Missing economies from the journal

Added missing economies

---

commodity.csv
happiness.csv
outfitting.csv

One new commodity and two new modules

September update

---

factionstate.csv

Added missing factionstates

---

outfitting.csv
sku.csv

Powerplay Grom

---

rare_commodity.csv

Use in-game display name instead of internal name for Apa Vietti, thanks to Gazelle (TD)
aka Berndulas#7599 for the hint

Add new rare trade good Apa Vietii

---

economy.csv
government.csv

Added the new government and economy types that fleet carriers will add.

Added fleet carrier economy & government types

---

commodity.csv
rare_commodity.csv

* `Duradrives` is a rare commodity
* `Nanomedicines` is a rare commodity

Duradrives and Nanomedicines are rare commodities

---

commodity.csv

The items from the ruins are now called `Guardian ...`

We got a name for the ancients.

---

material.csv

Material list

---

commodity.csv

The is a new commodity on the market.

New onionhead commodity

---

outfitting.csv

Based on a raw data save at Jameson Memorial by a Horizons commander, but should be equal for Odyssey

New multi limpet controllers

---

commodity.csv

New Guardian Relic with some Thargoid extension.

New commodity with update 13

---

outfitting.csv

First new modules from the Communitygoal series `Enhanced AX Project`, more to come.

Enhanced AX Multi-Cannon Turreted

---

outfitting.csv

Next two installments of the `Enhanced AX Project` community goals.

Enhanced AX Missile Rack (Turreted) and Enhanced AX Multi-Cannon (Fixed)

---

rare_commodity.csv

Just two minor name updates synced with current `Market.json`

Minor name updates of rare commodities

---

outfitting.csv

Fourth and fifth development of Enhanced AX weapons.

Enhanced AX Missile Rack (Fixed) and Multi-Cannon (Gimballed)

---

outfitting.csv

The elusive `Hpt_XenoScannerMk2_Basic_Tiny` got released.

Experimental Weapon Stabiliser (Class 3) and Enhanced Xeno Scanner

---

outfitting.csv

SKU (entitlement) still unknown

Caustic Sink Launcher and Thargoid Pulse Neutraliser

---

commodity.csv

* Impure Spire Mineral
* Semi-Refined Spire Mineral

2 new commodities with Update 17

---

outfitting.csv

Pulse scanner that gathers data about capital-class alien vessels. Intended for use with Thargoid Titans, though it can analyse smaller xeno vessels.

Pulse Wave Xeno Scanner

---

outfitting.csv

Two new guardians weapons with update 18

New weapons with update 18

---

rare_commodity.csv

see https://www.elitedangerous.com/en-GB/news/galnet/sandras-workshop-asks-festive-gift-couriers

Festive Gifts are back in Njambalba / Frost Dock
